#!/opt/perl/bin/perl

use 5.026;

use strict;
use warnings;
no  warnings 'syntax';
use autodie;

use experimental 'signatures';

my $input = "input";
open my $fh, "<", $input;
# chomp (my $line = do {local $/; <$fh>});
# chomp (my @lines = <$fh>);


__END__
