#!/opt/perl/bin/perl

use 5.026;

use strict;
use warnings;
no  warnings 'syntax';
use autodie;

use experimental 'signatures';

my $keypad = [[" "],
              [],
              map {[split //]} qw [abc def ghi jkl mno pqrs tuv wxyz]];

my $input = "input";
open my $fh, "<", $input;
while (<$fh>) {
    chomp;
    my ($digit, $times) = split ' ';
    print $$keypad [$digit] [$times - 1];
}
print "\n";

__END__
